unit tbDomainDTO;

interface

uses
  MVCFramework.ActiveRecord,
  MVCFramework.SQLGenerators.PostgreSQL{must for ActiveRecord};

type
  TCustomActiveRecord = class abstract(TMVCActiveRecord)
  protected
    procedure OnBeforeExecuteSQL(var SQL: string); override;
  end;

type
  [MVCTable('toybox.task')]
  [MVCEntityActions([eaCreate, eaUpdate, eaRetrieve])]
  TtbTaskDTO = class(TCustomActiveRecord)
  public
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    ID: Integer;
    Title: String;
    Text: String;
    Tags: String;
    Created_By: Integer;
    Assigned_To: Integer;
    Status: Integer;
  end;

implementation

uses
  MVCFramework.Logger;

{ TCustomActiveRecord }

procedure TCustomActiveRecord.OnBeforeExecuteSQL(var SQL: string);
begin
  inherited;
  Log.Info(ClassName + ' | ' + SQL, 'sql_trace');
end;

end.
